{% set name = "ZORRO" %}
{% set version = "2011.12.01" %}
{% set sha256 = "88103806fc578c4c590e42bbb4eb9a1efbd4b3f48dfabf3ca210492db2d3d9f8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url:
    - https://sourceforge.net/projects/probmask/files/probmask.tar.gz
    - https://depot.galaxyproject.org/software/zorro/zorro_2011.12.01_src_all.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5
  skip: true  # [osx]
  run_exports: # run_exports这个要配置上, 不然提交可能check不通过
    - {{ pin_subpackage('zorro', max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - autoconf
    - automake
  run:
    - perl
    - fasttree

test:
  commands:
    - zorro

about:
  home: https://sourceforge.net/projects/probmask/
  license: Apache License 2.0
  license_family: Apache
  summary: "ZORRO is a probabilistic masking program that assigns confidence scores to each column in a multiple sequence alignment."

extra: # 一般我们要加这个extra配置,指示aarch64架构也支持,但是如果在build下已经指示是noarch了,就不要加这个了
  additional-platforms:
    - linux-aarch64
