{% set name = "bamstats" %}
{% set version = "0.3.5" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1
  run_exports: # run_exports这个要配置上, 不然提交可能check不通过
    - {{ pin_subpackage('bamstats', max_pin="x.x") }}

source:
  - url: https://github.com/guigolab/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 0b397c0b09c4a944e564dd9e92eb5e9e8408e97cf1a54af07dced8783342b977

requirements:
  build:
    - go 

test:
  commands:
    - bamstats --help
    - bamstats --version

about:
  home: https://github.com/guigolab/bamstats
  license: BSD-3-Clause
  summary: A command line tool to compute mapping statistics from a BAM file
  license_file: LICENSE
